# 1.
name: Test & Build

# 2.
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master


# 3.git
jobs:
  main:
    runs-on: macos-latest

    # 4.
    steps:

      # 5.
      - name: Clone repository
        uses: actions/checkout@v4

      # 6.
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "18.x"

      # 7.
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.32.8'

      # 8.
      - name: Get Flutter packages
        run: |
          flutter pub get

      # 11.
      - name: Build APK
        run: |
          flutter build apk

      - name: Install CocoaPods
        run: |
          cd ios
          pod install
          cd ..
      
      # 12.
      - name: Flutter build ipa
        run: |
          flutter build ipa --no-codesign

      # 13.
      - name: Compress Archives and IPAs
        run: |
          cd build
          tar -czf ios_build.tar.gz ios

      # 14.
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Releases
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/ios_build.tar.gz
